[telegram]
api_id = "26831388"
api_hash = "43ad46e4d53c5ff1ca0e27c9ca4407b7"
bot_token = "7458801028:AAF2Ze8Ukd1faOI3SGo4nGFzKk6dOGyf9uE"
channel_id = 1001927626277

[vk]
token = "vk1.a.BujFws4sioTB7zJ3p5i40Aq9IVWhnnU910z1OCd2teuGXv4ZH2XrA8S-Tlab14XAWRl_OpmMuxHs4sG8-YE-xfWI9NDCE_uMBwFLQHP4njlLAJa8dKuldBPDIoG4GCs2__PEIi165kON4uni8_LB0rxfpC7RAGm4icDXQqrBrZIwkV8fGu1-Dh2V1sdNnVofVYQ_VOwK8rTbAXHkChA8tQ"
group_id = "29899402"